export component AppTray inherits SystemTrayIcon {
    in-out property <bool> tray-visible: true;
    in property <string> tray-tooltip-text;
    in property <string> tray-settings-text;
    in property <string> tray-quit-text;

    icon: @image-url("icon-small.png");
    visible: root.tray-visible;
    tooltip: root.tray-tooltip-text;
    title: root.tray-tooltip-text;

    Menu {
        MenuItem {
            title: root.tray-settings-text;
            activated => { root.open-settings(); }
        }

        MenuSeparator { }

        MenuItem {
            title: root.tray-quit-text;
            activated => { root.quit(); }
        }
    }

    clicked => { root.open-settings(); }

    callback open-settings();
    callback show-widgets();
    callback quit();
}

export component KeepAliveWindow inherits Window {
    width: 1px;
    height: 1px;
    title: "crypto-hud-keepalive";
    no-frame: true;
    background: transparent;
}
